name: Story Bot
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install gspread requests beautifulsoup4 python-telegram-bot schedule
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CHANNEL: ${{ secrets.CHANNEL_NAME }}
          CREDS: ${{ secrets.GDRIVE_CREDS }}
        run: |
          echo "$CREDS" > creds.json
          python bot.py
