name: Auto Story Bot (IST)
on:
  schedule:
    - cron: '30 18 * * *'  # ভারতীয় সময় 00:00 (UTC+5:30)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth schedule requests beautifulsoup4 python-telegram-bot
          
      - name: Run Story Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
          GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
        run: |
          echo "$GDRIVE_CREDS" > credentials.json
          python bot.py
