name: Auto Story Bot
run-name: ${{ github.actor }} is running the story bot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install gspread google-auth schedule requests beautifulsoup4 python-telegram-bot
          
      - name: Run Story Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
          GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
        run: |
  echo "$GDRIVE_CREDS" > credentials.json
  python bot.py

